GET http://localhost:3000/products/

###API-1
POST http://localhost:3000/products/
Content-Type: application/json

[{"productId":1,"quantity":17,"operation":"subtract"},
{"productId":2,"quantity":17,"operation":"subtract"},
{"productId":3,"quantity":17,"operation":"subtract"}]
